import _Exception from './_Exception.js'
import ApplicationException from './ApplicationException.js';
import BaseClient from './BaseClient.js';
import ColorClient from './ColorClient.js ';
import ElevationClient from './ElevationClient.js ';
import ElevationPointResult from './ElevationPointResult.js';
import ElevationResult from './ElevationResult.js';
import EventArgs from './EventArgs.js';
import GettingAccessTokenEventArgs from './GettingAccessTokenEventArgs.js';
import GradeResult from './GradeResult.js';
import GradeSegment from './GradeSegment.js';
import IDisposable from './IDisposable.js';
import ISerializable from './ISerializable.js';
import LocationCategories from './LocationCategories.js';
import MapProjection from './MapProjection.js';
import MapsClient from './MapsClient.js';
import ProjectionClient from './ProjectionClient.js';
import RasterMapType from './RasterMapType.js';
import ReverseGeocodingClient from './ReverseGeocodingClient.js';
import ReverseGeocodingLocation from './ReverseGeocodingLocation.js';
import ReverseGeocodingOptions from './ReverseGeocodingOptions.js';
import ReverseGeocodingResult from './ReverseGeocodingResult.js';
import ReverseGeocodingResultDetail from './ReverseGeocodingResultDetail.js';
import ThinkGeoCloudApplicationException from './ThinkGeoCloudApplicationException.js';
import TileResolution from './TileResolution.js';
import TileSize from './TileSize.js';

let T = {};

T._Exception = _Exception;
T.ApplicationException = ApplicationException;
T.BaseClient = BaseClient;
T.ColorClient = ColorClient;
T.ElevationClient = ElevationClient;
T.ElevationPointResult = ElevationPointResult;
T.ElevationResult = ElevationResult;
T.EventArgs = EventArgs;
T.GettingAccessTokenEventArgs = GettingAccessTokenEventArgs;
T.GradeResult = GradeResult;
T.GradeSegment = GradeSegment;
T.IDisposable = IDisposable;
T.ISerializable = ISerializable;
T.LocationCategories = LocationCategories;
T.MapProjection = MapProjection;
T.MapsClient = MapsClient;
T.ProjectionClient = ProjectionClient;
T.RasterMapType = RasterMapType;
T.ReverseGeocodingClient = ReverseGeocodingClient;
T.ReverseGeocodingLocation = ReverseGeocodingLocation;
T.ReverseGeocodingOptions = ReverseGeocodingOptions;
T.ReverseGeocodingResult = ReverseGeocodingResult;
T.ReverseGeocodingResultDetail = ReverseGeocodingResultDetail;
T.ThinkGeoCloudApplicationException = ThinkGeoCloudApplicationException;
T.TileResolution = TileResolution;
T.TileSize = TileSize;

export default T;